Resources:
  NametagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.stage}-nametags
      AttributeDefinitions:
        - AttributeName: tagId
          AttributeType: S
      KeySchema:
        - AttributeName: tagId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}